export interface Corporator {
  srNo: number;
  wardNo: number;
  seat: string;
  name: string;
  address: string;
  party: string;
}

export const CORPORATORS: Corporator[] = [
  { srNo: 1, wardNo: 1, seat: "1-A", name: "Navare Rupali Swapnil", address: "S.No.158/2/1, Flat No.14, Gokuldhaam Residency, Tarawala Nagar, Lamkhede Mala, Panchavati, Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 2, wardNo: 1, seat: "1-B", name: "Bhansi Ranjana Popat", address: "7 B. Ketki Housing Society, Mhasarul, Nashik 422004", party: "Bharatiya Janata Party" },
  { srNo: 3, wardNo: 1, seat: "1-C", name: "Dipali Ganesh Gite", address: "1, Satyam Row-Bungalow, Pokar Colony, Kalanagar, Dindori Road, Nashik - 422004", party: "Bharatiya Janata Party" },
  { srNo: 4, wardNo: 1, seat: "1-D", name: "Pravin Mandakini Ramesh Jadhav", address: "54, Ashirvad, Goraksha Nagar, Meri-RTO Link Road, Dindori Road, Nashik - 422004", party: "Shiv Sena" },
  { srNo: 5, wardNo: 2, seat: "2-A", name: "Aishwarya Lad - Jejurkar", address: "Gurukrupa Bungalow, Jejurkar Mala, Chh. Sambhajinagar Road, Panchavati, Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 6, wardNo: 2, seat: "2-B", name: "Indubai Suresh Khetade", address: "Flat No.1 A Wing, Dwarkadhish Apartment, Vrundavan Nagar, Adgaon Shivar, Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 7, wardNo: 2, seat: "2-C", name: "Riddhish Udhav Nimse", address: "Kavita Bungalow, Near Laxmivijay Lawns, Nandur, Po. Madsangavi, Tal. Dist. Nashik", party: "Bharatiya Janata Party" },
  { srNo: 8, wardNo: 2, seat: "2-D", name: "Adv. Namdev Nivrutti Shinde", address: "Mu.Po.Adgaon, Tal.Dist. Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 9, wardNo: 3, seat: "3-A", name: "Mane Priyanka Dhananjay", address: "Plot No. 24/2, Suman-Bhaskar Nivas, Mane Nagar, Rasbhari-Meri Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 10, wardNo: 3, seat: "3-B", name: "Jui Pranav Shinde", address: "1204 D Wing, Kanha, Samrat Vrundavan, Om Nagar, Panchavati, Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 11, wardNo: 3, seat: "3-C", name: "Sanap Machhindra Balasaheb", address: "Krishnakunj Bungalow, Krishnanagar, Juna Adgaon Naka, Panchavati, Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 12, wardNo: 3, seat: "3-D", name: "Govardhane Gaurav Bhanudas", address: "02, Rudra Heights, Shaktinagar, Hiravadi, Panchavati, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 13, wardNo: 4, seat: "4-A", name: "Hire Monika Shankar", address: "House No.70, Rahulwadi, Peth Road, Panchavati, Nashik - 3", party: "Bharatiya Janata Party" },
  { srNo: 14, wardNo: 4, seat: "4-B", name: "Sonwane Sarita Ramrao", address: "Flat No.7, Vimla Apartment, Shakti Nagar, Hiravadi, Panchavati, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 15, wardNo: 4, seat: "4-C", name: "Engr. Sagar Hiraman Lamkhade", address: "C.D.O. Meri Office Gopal Krupa Farm, Lamkhede Mala, Dindori Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 16, wardNo: 4, seat: "4-D", name: "Shetty Hemant Dinesh", address: "4, Shrikrushna Society, Shrikrushna Nagar, Panchavati, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 17, wardNo: 5, seat: "5-A", name: "Bodake Kamlesh Mohan", address: "Plot No. 51, Ramshej Darshan, Dattnagar, Peth Road, Panchavati, Nashik", party: "Shiv Sena" },
  { srNo: 18, wardNo: 5, seat: "5-B", name: "Dhumal Chandrakala Sandesh", address: "House No. 4217, Nagchowk, Panchavati, Nashik 422003", party: "Bharatiya Janata Party" },
  { srNo: 19, wardNo: 5, seat: "5-C", name: "Nilam Naresh Patil", address: "9, Aradhana Bungalow, New Mahavir Society, Rohini Nagar, Peth Road, Nashik 422003", party: "Bharatiya Janata Party" },
  { srNo: 20, wardNo: 5, seat: "5-D", name: "Bagga Gurmeet Arjunsingh", address: "4409, Bagga Nivas Panchavati, Nashik 422003", party: "Bharatiya Janata Party" },
  { srNo: 21, wardNo: 6, seat: "6-A", name: "Chitra Jagannath Tandale", address: "Flat No. 1, Saibhakti Apartment, Near Saibaba Mandir, Behind Irrigation Colony, Makhmalabad, Tal. Dist. Nashik", party: "Bharatiya Janata Party" },
  { srNo: 22, wardNo: 6, seat: "6-B", name: "Walu (Pahlwan) Vishwanath Kakad", address: "Matori Road, Gopal Nagar, Kakad Mala, Makhmalabad, Nashik - 422003", party: "Bharatiya Janata Party" },
  { srNo: 23, wardNo: 6, seat: "6-C", name: "Pingle Rohini Bapurao", address: "Amardhaam Road, Devichi Mala, Makhmalabad, Tal.Dist. Nashik 422003", party: "Bharatiya Janata Party" },
  { srNo: 24, wardNo: 6, seat: "6-D", name: "Pramod (Bapu) Devram Palve", address: "Kakad Galli, Main Road, Makhmalabad, Nashik", party: "Shiv Sena" },
  { srNo: 25, wardNo: 7, seat: "7-A", name: "Patil Suresh Annaji", address: "38-Shradha, Anandvan Colony, College Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 26, wardNo: 7, seat: "7-B", name: "Aher Himgauri Balasaheb", address: "Girija Bungalow, Pumping Station, Gangapur Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 27, wardNo: 7, seat: "7-C", name: "Bhamre Swati Rajeev", address: "Flat No.201, Liberty Harmony, Saubhagya Nagar, Gangapur Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 28, wardNo: 7, seat: "7-D", name: "Boraste Ajay Bhaskarrao", address: "Renuka Nivas, Plot No. 8, Sahdev Nagar, Gangapur Road, Nashik", party: "Shiv Sena" },
  { srNo: 29, wardNo: 8, seat: "8-A", name: "Lokhande Kavita Dashrath", address: "House No. 105/200, Rajwada, Anandvalli Nashik", party: "Bharatiya Janata Party" },
  { srNo: 30, wardNo: 8, seat: "8-B", name: "Bendkoli Usha Hiraman", address: "Bendkule Nagar, Anandvalli Nashik 422013", party: "Bharatiya Janata Party" },
  { srNo: 31, wardNo: 8, seat: "8-C", name: "Ankita Mahendra Shinde", address: "Plot No. 11, Parvati Nivas, Hanuman Mandir, Sadguru Nagar, Satpur Nashik", party: "Bharatiya Janata Party" },
  { srNo: 32, wardNo: 8, seat: "8-D", name: "Shinde Vilas Ramdas", address: "Anusaya Bungalow, Near Patil Lawns, Gangapur Road, Nashik", party: "Shiv Sena" },
  { srNo: 33, wardNo: 9, seat: "9-A", name: "Bharati Ravindra Dhivare", address: "Gautami Nivas Room No. 2, Tulja Apartment Plot No. 64, S.N. 193, Behind Carbon Nakya, Shramik Nagar, Satpur Nashik - 12", party: "Bharatiya Janata Party" },
  { srNo: 34, wardNo: 9, seat: "9-B", name: "Dinkar Dharma Patil", address: "Sarvadnya Bungalow, Shivajinagar, Gangapur Shivar, Satpur, Nashik 422012", party: "Bharatiya Janata Party" },
  { srNo: 35, wardNo: 9, seat: "9-C", name: "Sangita Balasaheb Ghotekar", address: "Plot No. 51/B, Gat No. 194, Kundan Nivas, Mali Colony, Shramik Nagar, Satpur, Nashik 422012", party: "Bharatiya Janata Party" },
  { srNo: 36, wardNo: 9, seat: "9-D", name: "Amol Dinkar Patil", address: "Sarvadnya Bungalow, Shivajinagar, Gangapur Shivar, Satpur, Nashik 422102", party: "Bharatiya Janata Party" },
  { srNo: 37, wardNo: 10, seat: "10-A", name: "Vishwas Chintaman Nagare", address: "Shivatirtha Nivas, Pimplgaon Bahula, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 38, wardNo: 10, seat: "10-B", name: "Indubai Sudam Nagare", address: "Flat No. 3, Indu Palace, Nagare Chowk, Ashok Nagar, Nashik", party: "Shiv Sena" },
  { srNo: 39, wardNo: 10, seat: "10-C", name: "Bolkar Madhuri Ganesh", address: "Plot No. 20, Shrisamarth Nivas, Papaya Nursery, Tryambak Road, Satpur, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 40, wardNo: 10, seat: "10-D", name: "Samadhan Namdev Devre", address: "Plot No. 37, Raygad, State Employees Colony, Ashok Nagar, Satpur Nashik", party: "Bharatiya Janata Party" },
  { srNo: 41, wardNo: 11, seat: "11-A", name: "Savita Ravindra Kale", address: "House No. 578, Dr. Ambedkar Chowk, Rajwada, Satpur, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 42, wardNo: 11, seat: "11-B", name: "Manasi Yogesh Shevre", address: "Plot No. 32, Gat No. 498, Lal Bahadur Shastri, Ashok Nagar, Satpur, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 43, wardNo: 11, seat: "11-C", name: "Bhandure Sonali Tushar", address: "B-1, Samarth Bungalow, Rajshri Garden, Sandip Nagar, Ashok Nagar, Satpur Nashik", party: "Bharatiya Janata Party" },
  { srNo: 44, wardNo: 11, seat: "11-D", name: "Nitin (Bala) Sampatrao Nigal", address: "House No. 844, Gorakshanath Road, Gorakshanath Mandir, Nigal Mala, Satpur Nashik", party: "Bharatiya Janata Party" },
  { srNo: 45, wardNo: 13, seat: "12-A", name: "Aher Rajendra Vinayak", address: "Plot No. 46, Sambhaji Chowk, City Centre Mall, Lavate Nagar, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 46, wardNo: 12, seat: "12-B", name: "Thakare Sima Ranjan", address: "Sadhnika No.2, Dhanlaxmi Apartment, Mahatma Nagar, Nashik 422007", party: "Nationalist Congress Party" },
  { srNo: 47, wardNo: 12, seat: "12-C", name: "Dr. Sou. Hemlata Ninad Patil", address: "Daulat Bungalow, Tilakwadi, Ravbahadur Gokhale Road, Nashik", party: "Nationalist Congress Party" },
  { srNo: 48, wardNo: 12, seat: "12-D", name: "Kamble Sameer Uttamrao", address: "Uttam Nivas, 480 Q, Sharanpur Road, Near St. Andrea Church, Nashik 422002", party: "Shiv Sena" },
  { srNo: 49, wardNo: 13, seat: "13-A", name: "Pande Aditi Rituraj", address: "Plot No.47, Kishor Bungalow, Magh Sector E, Near Bhujbal Farm, CIDCO, Nashik, 422009", party: "Bharatiya Janata Party" },
  { srNo: 50, wardNo: 13, seat: "13-B", name: "Mayuri Ankush Pawar", address: "House No. 1882/83, Tivandha Chowk, Near Sakshi Ganesh Mandir, Bhadrakali, Nashik - 1", party: "Maharashtra Navnirman Sena" },
  { srNo: 51, wardNo: 13, seat: "13-C", name: "Rahul (Bablu Bhau) Shantaram Shelar", address: "3254, Kamod Road, Bagwanpura, Nashik, 422 001", party: "Bharatiya Janata Party" },
  { srNo: 52, wardNo: 13, seat: "13-D", name: "Khaire Shahu Sahdevrao", address: "H.No. 2248, Near Modakeshwar Mandir, Nav Darwaja, Nashik 422001", party: "Bharatiya Janata Party" },
  { srNo: 53, wardNo: 14, seat: "14-A", name: "Gangurde Jagruti Dattu", address: "H.No. 3892, Manur Road, Near Nanavali Masjid, Nanavali, Nashik 422001", party: "Nationalist Congress Party" },
  { srNo: 54, wardNo: 14, seat: "14-B", name: "Najiya Jakir Attar", address: "H.No.2719, Kajipura, Juna Nashik, Nashik City - 422 001", party: "Indian National Congress" },
  { srNo: 55, wardNo: 14, seat: "14-C", name: "Samiya Sumer Khan", address: "Flat No. 6, 3rd Floor, Raja Palace Building, Wadala Road, Madina Chowk, Nashik - 422001", party: "Indian National Congress" },
  { srNo: 56, wardNo: 14, seat: "14-D", name: "Sufiyan Ibrahim Jeen (Sufi)", address: "House No. 2793, Near Phule Market, Kokanipura, Nashik - 422 001", party: "Indian National Congress" },
  { srNo: 57, wardNo: 15, seat: "15-A", name: "Gite Prathamesh Vasant", address: "Kamal Nivas, Dr. Bhabha Nagar, Mumbai Naka, Nashik, 422011", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 58, wardNo: 15, seat: "15-B", name: "Sima Vishal Pawar", address: "SaiShubh, 29 Lane No. 3, Kathe Nagar, Kathe Galli, Dwarka, Nashik, 422 011", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 59, wardNo: 15, seat: "15-C", name: "Marathe Sachin Ramesh", address: "4, Truptida Housing Society, Bungalow No. 4, Takli Road, Behind Dwarka Hotel, Dwarka, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 60, wardNo: 16, seat: "16-A", name: "Dive Rahul Ashok", address: "Ra Bhau Bungalow, Agar Takli Road, Nashik", party: "Shiv Sena" },
  { srNo: 61, wardNo: 16, seat: "16-B", name: "Tadvi Asha Rafique", address: "Plot No. 5, Krishna Paradise, Kathe Nagar, Upanagar, Nashik", party: "Shiv Sena" },
  { srNo: 62, wardNo: 16, seat: "16-C", name: "Pooja Pravin Navale", address: "13, Shivkrupa, Shram Nagar, Upanagar Gandhinagar, Nashik", party: "Shiv Sena" },
  { srNo: 63, wardNo: 16, seat: "16-D", name: "Jondhale Jyoti Anil", address: "Kashi Nivas, Ramdas Swami Nagar, Behind Gandhi Nagar, Upanagar, Nashik 422006", party: "Shiv Sena" },
  { srNo: 64, wardNo: 17, seat: "17-A", name: "Dive Prashant Ashok", address: "Dive Bungalow, Agar Takli, Gandhinagar, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 65, wardNo: 17, seat: "17-B", name: "Adhav Mangala Prakash", address: "Datta Anusaya Bungalow, Opp. Maruti Mandir, Dasak Village, Jail Road, Nashik Road, Tal.Dist. Nashik 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 66, wardNo: 17, seat: "17-C", name: "Maind Pramila Kailash", address: "408, B-Wing, Hari Vihar Housing Society, Narayanbapoo Nagar, Near Bachhav Class, Jail Road, Nashik Road, Tal.Dist.Nashik 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 67, wardNo: 17, seat: "17-D", name: "Dhage Shailendra Atmaram", address: "1,2, Tryambak Darshan Society, Shriram Nagar, Dasak, Jail Road, Nasik Road, 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 68, wardNo: 18, seat: "18-A", name: "Sharad Draupada Chintaman More (Sir)", address: "More Mala, Pimpalwadi, Panchak, Jail Road, Nashik Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 69, wardNo: 18, seat: "18-B", name: "Ranjana Prakash Borade", address: "Damodhar Nagar, Juna Saikheda Road, Panchak, Borade Mala, Jail Road, Nashik Road, Tal.Dist. Nashik 422101", party: "Shiv Sena" },
  { srNo: 70, wardNo: 18, seat: "18-C", name: "Sunita Sagar Bhojane", address: "Shiv Sukh Apartment, Flat No. 06, Jagruti Nagar, Panchak, Jail Road, Nashik Road, Nashik 422101", party: "Shiv Sena" },
  { srNo: 71, wardNo: 18, seat: "18-D", name: "Vishal Uttam Sangamnere", address: "Flat No.67, Pragati Nagar, Jail Road, Panchak, Nashik Road, Tal.Dist. Nashik 422101", party: "Bharatiya Janata Party" },
  { srNo: 72, wardNo: 19, seat: "19-A", name: "Ruchira Santosh Salve", address: "Reshma Nivas, Shastri Nagar, Gorewadi, Nashik Road, Tal Dist Nashik 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 73, wardNo: 19, seat: "19-B", name: "Yogesh Waman Bhor", address: "Bhor Mala, Near Om Tulja Lawns, Samangaon Road, Nashik Road, Tal.Dist. Nashik 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 74, wardNo: 19, seat: "19-C", name: "Bharati Ambadas Tajanpure", address: "Punam Nivas, Chehedi Pumping, Nashik Road, Tal.Dist. Nashik 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 75, wardNo: 20, seat: "20-A", name: "Satish Anandrao Nikam", address: "05, Mahesh, Nashik-Pune Road, Opp. Siddharth Hotel, Gayatri Nagar, Tal.Dist.Nashik 422011", party: "Bharatiya Janata Party" },
  { srNo: 76, wardNo: 20, seat: "20-B", name: "Tajane Sima Rajendra", address: "Flat No.13, Bhakti Apartment, Kalanagar, Bitko Chowk, Jail Road, Nashik Road, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 77, wardNo: 20, seat: "20-C", name: "Gaikwad Jayashri Ajit", address: "D-5, Jaymahalaxmi Society, Gaikwad Mala, Nashik Road - 422101, Tal.Dist.Nashik", party: "Bharatiya Janata Party" },
  { srNo: 78, wardNo: 20, seat: "20-D", name: "Kailash (Anna) Suresh Mudliyar", address: "9, Nandan Park, Gandharvanagari, Nashik Road, Nashik", party: "Shiv Sena" },
  { srNo: 79, wardNo: 21, seat: "21-A", name: "Adv. Komal Pratap Mehroliya (Girdhar)", address: "Wescon Vista Flat No.601, Wadala Road, Indira Nagar, Nashik - 422009", party: "Bharatiya Janata Party" },
  { srNo: 80, wardNo: 21, seat: "21-B", name: "Dhongade Ramesh Shankar (R.D.)", address: "B-8, Ashok Vihar, Datta Mandir Road, Dhongade Mala, Nashik Road, Tal.Dist Nashik 422101", party: "Shiv Sena" },
  { srNo: 81, wardNo: 21, seat: "21-C", name: "Bhandari Shweta Nirmal", address: "Flat No.10/11, Sairatan Residency B, Motwani Road", party: "Bharatiya Janata Party" },
  { srNo: 82, wardNo: 21, seat: "21-D", name: "Jachak Jayant Ashok", address: "01, Saidisha Apartment, Jachak Nagar, Jaybhawani Road", party: "Bharatiya Janata Party" },
  { srNo: 83, wardNo: 22, seat: "22-A", name: "Dani Vaishali Pramod", address: "Flat No. A-3, Shri Sambhav Society, Lam Road, Vihitgaon, Tal.Dist.Nashik", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 84, wardNo: 22, seat: "22-B", name: "Gadekar Yogesh Laxman", address: "Gadekar Mala, Juna Chehedi Road, Nashik Road, Nashik - 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 85, wardNo: 22, seat: "22-C", name: "Sanjeevani Sanjay Handore", address: "Handore Mala, Vadner Road, Near Shri Karbhari Baba Mandir, Vihitgaon, Nashik - 422101", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 86, wardNo: 22, seat: "22-D", name: "Porje Keshav Sitaram", address: "Mahakali Chowk, Vadner Dumala, Tal.Dist.Nashik 422401", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 87, wardNo: 23, seat: "23-A", name: "Rupali Yashwant Nikule", address: "Tailoring & Hobby Classes, Shri Ganesh Bungalow, Amrutvasha Colony, Sainath Nagar, 422006", party: "Bharatiya Janata Party" },
  { srNo: 88, wardNo: 23, seat: "23-B", name: "Mangala Prakash Nannavare", address: "Plot No. 6, Sarvadnya Bungalow, Wadala Road, Near Devi Mandir, Tagore Nagar, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 89, wardNo: 23, seat: "23-C", name: "Kulkarni Sandhya Abhijit", address: "Business Training Institute, Row House No. 5, Adishakti Rathchakra Chowk, Indira Nagar, Nashik 422009", party: "Bharatiya Janata Party" },
  { srNo: 90, wardNo: 23, seat: "23-D", name: "Khode Chandrakant Karbhari", address: "109/9, Anusuyasut Bungalow, Opposite Gajra Nisarga Twins Bungalow, Indira Nagar, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 91, wardNo: 24, seat: "24-A", name: "Sou. Pallavi Rahul Ganore", address: "N-9/M-2/20/1, Juna CIDCO, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 92, wardNo: 24, seat: "24-B", name: "Pravin (Bunty) Tidme", address: "N-3/L-15, Chh. Shivaji Maharaj Chowk, Juna CIDCO, Nashik", party: "Shiv Sena" },
  { srNo: 93, wardNo: 24, seat: "24-C", name: "Dr. Punam Yogesh Mahale", address: "Mahale Farm, Maharaja Pratap Chowk, Navin CIDCO, Nashik", party: "Shiv Sena" },
  { srNo: 94, wardNo: 24, seat: "24-D", name: "Mahale Rajendra (Bhau) Uttamrao", address: "Mahale Farm, Maharana Pratap Chowk, CIDCO, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 95, wardNo: 25, seat: "25-A", name: "Badgujar Sudhakar Bhika", address: "Plot No.94, Swami Nivas, Suryoday Colony, Savata Nagar, CIDCO, Nashik - 422008", party: "Bharatiya Janata Party" },
  { srNo: 96, wardNo: 25, seat: "25-B", name: "Matale Sadhana Pawan", address: "Flat No.7, Brahmasavitri Apartment, Durga Nagar, Kamtawade, Nashik - 422008", party: "Bharatiya Janata Party" },
  { srNo: 97, wardNo: 25, seat: "25-C", name: "Kavita Amol Naik", address: "Flat No.C-11, Amar Vrundavan Apartment, Naik Farm, Untwadi, CIDCO, Navin Nashik - 08", party: "Shiv Sena" },
  { srNo: 98, wardNo: 25, seat: "25-D", name: "Bhamre Murlidhar (Tatya) Sakharam", address: "N-42, VHA-1/1/1, Bhagwati Chowk, Savata Nagar, CIDCO, Nashik - 422008", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 99, wardNo: 26, seat: "26-A", name: "Ingole Nivrutti Haribhau", address: "171/0241, Near Maruti Mandir, Chunchale Village, Ambad, Nashik", party: "Shiv Sena" },
  { srNo: 100, wardNo: 26, seat: "26-B", name: "Gaykar Harshada Samadhan", address: "House No.212/213, DGP Nagar-3, Near Ganpati Mandir, Kamtawade, Nashik - 422008", party: "Shiv Sena" },
  { srNo: 101, wardNo: 26, seat: "26-C", name: "Jadhav Nayana Nilesh", address: "101, Space Whatsar, Patil Lane No.4, College Road, Nashik - 422005", party: "Shiv Sena" },
  { srNo: 102, wardNo: 26, seat: "26-D", name: "Arote Bhagwat Paraji", address: "Shivkrupa, Plot No.67, Gat No.37/1, Ramkrushna Nagar, Chunchale, Nashik - 10", party: "Shiv Sena" },
  { srNo: 103, wardNo: 27, seat: "27-A", name: "Donde Priyanka Rakesh", address: "House No. 421/47, Shantai Bungalow, Near Buddha Vihar, Donde Chowk, Ambad, Nashik - 422010", party: "Bharatiya Janata Party" },
  { srNo: 104, wardNo: 27, seat: "27-B", name: "Kiran Vasantrao Rajwade", address: "Behind Datta Mandir, Morvadi Village, Navin Nashik 422009", party: "Nationalist Congress Party" },
  { srNo: 105, wardNo: 27, seat: "27-C", name: "Engr. Kirantai Punjaram Gamane (Darade)", address: "A.S.C. 34, Near Minatai Thackeray Udyan, Ashwinnagar, CIDCO, Nashik", party: "Shiv Sena" },
  { srNo: 106, wardNo: 27, seat: "27-D", name: "Datir Nitin Pandit", address: "Behind Sumit Company, MIDC Ambad, Tal.Dist. Nashik", party: "Shiv Sena" },
  { srNo: 107, wardNo: 28, seat: "28-A", name: "Datir Deepak Nivrutti", address: "House No.463-A, Behind Pranay Stamping, Navnath Nagar, Ambad - 422010", party: "Shiv Sena" },
  { srNo: 108, wardNo: 28, seat: "28-B", name: "Pawar Pratibha Balasaheb", address: "Flat No.9, Vaidehi (B) Apartment, Sant Janardan Swami Nagar, Ambad, Nashik 422010", party: "Bharatiya Janata Party" },
  { srNo: 109, wardNo: 28, seat: "28-C", name: "Matale Suvarna Dipak", address: "Shivprabha, Plot No.8, Near Mayur Hospital, Anand Nagar, Jadhav Complex, Kamtawade, Nashik 422010", party: "Shiv Sena" },
  { srNo: 110, wardNo: 28, seat: "28-D", name: "Sharad (Bhau) Hari Bhau Fadol", address: "Fadol Mala, DGP Nagar No.2, Ambad Khurd, Nashik 422010", party: "Bharatiya Janata Party" },
  { srNo: 111, wardNo: 29, seat: "29-A", name: "Shahane Mukesh Dilip", address: "N-42/SC 2/19/8, Shanti Chowk, Pawan Nagar, CIDCO, Nashik", party: "Independent" },
  { srNo: 112, wardNo: 29, seat: "29-B", name: "Yogita (Vahini) Apurva Hire", address: "Flat No.301, Abode Apartment, Plot No.122, S.No.728/1 to 10, Near Ganpati Mandir, Mahatma Nagar, Nashik - 422007", party: "Bharatiya Janata Party" },
  { srNo: 113, wardNo: 29, seat: "29-C", name: "Devang Chhaya Dilip", address: "Flat No.11, Building No. 1, Shubham Park, Ambad Link Road, Navin Nashik - 10", party: "Bharatiya Janata Party" },
  { srNo: 114, wardNo: 29, seat: "29-D", name: "Bhushan Suresh Rane", address: "N-53/S.F.-3/27/5, Uttam Nagar, CIDCO, Nashik 422009", party: "Bharatiya Janata Party" },
  { srNo: 115, wardNo: 30, seat: "30-A", name: "Adv. Shyam Dharmaraj Badode", address: "Royal Hard Row-House No. 8, Wadala Pathardi Road, Opp. Bottle Factory, Indira Nagar, Nashik", party: "Bharatiya Janata Party" },
  { srNo: 116, wardNo: 30, seat: "30-B", name: "Khode Supriya Sunil", address: "Matoshri Bungalow, Khode Nagar, Pakhal Road, Nashik 422006", party: "Bharatiya Janata Party" },
  { srNo: 117, wardNo: 30, seat: "30-C", name: "Dr. Kulkarni Dipali Sachin", address: "11, Saishradha Apartment, Behind Saptashrungi Dairy, Pathchakra Chowk, Indira Nagar, Nashik 9", party: "Bharatiya Janata Party" },
  { srNo: 118, wardNo: 30, seat: "30-D", name: "Sane Ajinkya Vijay", address: "10, Kasturi Bungalow, Behind Shrijay Nagar, Wadala Pathardi Road, Indira Nagar, Nashik 422006", party: "Bharatiya Janata Party" },
  { srNo: 119, wardNo: 31, seat: "31-A", name: "Bhagwan Sukdev Donde", address: "Mu. Po. Pathardi, Tal. Dist. Nashik 422010", party: "Bharatiya Janata Party" },
  { srNo: 120, wardNo: 31, seat: "31-B", name: "Madhuri Madan Demse", address: "House No. 423/1878/Survey No.64/3, Nandur Road, Pathardi Village, Nashik, Tal.Dist. Nashik - 422010", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 121, wardNo: 31, seat: "31-C", name: "Vaishali Vinod Dalvi (Patil)", address: "Row House No. 1/2, Gurudhan Row Bungalow, Survey No. 895/2/3/1, Plot No.28, Saraf Nagar, CIDCO Colony, Nashik", party: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { srNo: 122, wardNo: 31, seat: "31-D", name: "Balkrushna Chandrabhaan Shirsath", address: "Gajraj Row-House No.05, Opp. Ganpati Mandir Metro Zone, Wadala Pathardi Road, Nashik 422010", party: "Bharatiya Janata Party" },
];

export function getCorporatorsByWard(wardNo: number): Corporator[] {
  return CORPORATORS.filter((c) => c.wardNo === wardNo).sort((a, b) => a.seat.localeCompare(b.seat));
}

export function getCorporator(srNo: number): Corporator | null {
  return CORPORATORS.find((c) => c.srNo === srNo) ?? null;
}
